/**
 * Common IANA timezones for the timezone dropdown.
 * Sorted by UTC offset, then alphabetically.
 */

export const TIMEZONE_OPTIONS = [
  { value: "Pacific/Midway", label: "(UTC-11:00) Midway Island" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(UTC-09:00) Alaska" },
  { value: "America/Los_Angeles", label: "(UTC-08:00) Pacific Time (US)" },
  { value: "America/Tijuana", label: "(UTC-08:00) Tijuana" },
  { value: "America/Denver", label: "(UTC-07:00) Mountain Time (US)" },
  { value: "America/Phoenix", label: "(UTC-07:00) Arizona" },
  { value: "America/Chihuahua", label: "(UTC-07:00) Chihuahua" },
  { value: "America/Chicago", label: "(UTC-06:00) Central Time (US)" },
  { value: "America/Mexico_City", label: "(UTC-06:00) Mexico City" },
  { value: "America/Costa_Rica", label: "(UTC-06:00) Costa Rica" },
  { value: "America/New_York", label: "(UTC-05:00) Eastern Time (US)" },
  { value: "America/Bogota", label: "(UTC-05:00) Bogotá" },
  { value: "America/Lima", label: "(UTC-05:00) Lima" },
  { value: "America/Panama", label: "(UTC-05:00) Panama" },
  { value: "America/Caracas", label: "(UTC-04:00) Caracas" },
  { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
  { value: "America/Halifax", label: "(UTC-04:00) Atlantic Time" },
  { value: "America/La_Paz", label: "(UTC-04:00) La Paz" },
  { value: "America/Santo_Domingo", label: "(UTC-04:00) Santo Domingo" },
  { value: "America/St_Johns", label: "(UTC-03:30) Newfoundland" },
  { value: "America/Sao_Paulo", label: "(UTC-03:00) São Paulo" },
  { value: "America/Argentina/Buenos_Aires", label: "(UTC-03:00) Buenos Aires" },
  { value: "Atlantic/South_Georgia", label: "(UTC-02:00) South Georgia" },
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { value: "UTC", label: "(UTC+00:00) UTC" },
  { value: "Europe/London", label: "(UTC+00:00) London" },
  { value: "Africa/Casablanca", label: "(UTC+00:00) Casablanca" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Berlin" },
  { value: "Europe/Paris", label: "(UTC+01:00) Paris" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Madrid" },
  { value: "Europe/Rome", label: "(UTC+01:00) Rome" },
  { value: "Africa/Lagos", label: "(UTC+01:00) Lagos" },
  { value: "Europe/Athens", label: "(UTC+02:00) Athens" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) Johannesburg" },
  { value: "Europe/Istanbul", label: "(UTC+03:00) Istanbul" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Riyadh" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Dubai" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Karachi" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) India (IST)" },
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "Asia/Yangon", label: "(UTC+06:30) Yangon" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
  { value: "Asia/Ho_Chi_Minh", label: "(UTC+07:00) Ho Chi Minh City" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) Beijing / Shanghai" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "Asia/Manila", label: "(UTC+08:00) Manila" },
  { value: "Australia/Perth", label: "(UTC+08:00) Perth" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
  { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "Australia/Sydney", label: "(UTC+10:00) Sydney" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Guam" },
  { value: "Pacific/Noumea", label: "(UTC+11:00) Noumea" },
  { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
];
